name: onlala_suppliers
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_slider: ^2.1.0
  introduction_screen: ^1.0.8
  shared_preferences: ^0.5.7+1
  file_picker: ^1.9.0+1
  url_launcher: ^5.4.5
  flutter_svg: ^0.17.4
  flutter_full_pdf_viewer: ^1.0.6
  image_cropper: ^1.2.1
  chewie: ^0.9.10
  video_player: ^0.10.10
  provider: 
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/icons/
   - assets/img/
